service: blog-shooksweb

provider:
  name: aws

plugins:
  - serverless-finch

custom:
  noCache:
    - name: "Cache-Control"
      value: "public, max-age=0, must-revalidate"
  permanentCache:
    - name: "Cache-Control"
      value: "public, max-age=31536000, immutable"
  client:
    bucketName: shooksweb-blog-${opt:stage, 'dev'}
    distributionFolder: public
    objectHeaders:
      ALL_OBJECTS: ${self:custom.noCache}
      "static/*": ${self:custom.permanentCache}
      "**/*.js": ${self:custom.permanentCache}
      "**/*.css": ${self:custom.permanentCache}
      "sw.js": ${self:custom.noCache}
